@startuml

title <b> Diagrama de Caso de Uso Musicáudio </b>

left to right direction

'atores
:aluno:
:professor:
:usuario:

'casos de uso

(Gerenciar Forma de Pagamento)

(Gerenciar Perfil)

(Gerenciar Cursos)
(Gerenciar Aulas)
(Upload de Materiais)

(Realizar Cursos)

'relacionamentos
professor --> (Gerenciar Cursos)
aluno --> (Realizar Cursos)
aluno --> (Gerenciar Forma de Pagamento)
usuario --> (Gerenciar Perfil)

usuario <|-- aluno
usuario <|-- professor

(Gerenciar Cursos) <-- (Gerenciar Aulas) : extend
(Gerenciar Aulas) <-- (Upload de Materiais) : extend

@enduml