@startuml
title Diagrama de Implantação - Musicáudio

skinparam backgroundColor lightyellow
skinparam componentStyle rectangle
skinparam DefaultTextAlignment center

node "Dispositivo do Usuário" <<device>> #white {
  artifact "Navegador Web" as browser 
}

node "Servidor Front-end\nNode.js / Vite" as frontend <<server>> #white {
  artifact "Aplicação Vue.js" as vue <<artifact>>
}

node "Servidor Back-end" as backend <<server>> #white {

 component "Aplicação Spring Boot" as spring <<artifact>>

  database "Banco de Dados\nPostgreSQL" as postgres <<database>> #white 
}

browser --> vue : HTTPS

vue --> spring

spring --> postgres


note right of frontend
Front-end desenvolvido com:
- Vue.js
- Vue Router
- Pinia
- Axios
- Vite
end note

note right of backend
Back-end desenvolvido com:
- Spring Boot
- Spring Web
- Spring Data JPA
- Spring Security
- JWT
end note

@enduml