@startuml
title Diagrama de Implantação - Musicáudio

skinparam backgroundColor lightyellow
skinparam componentStyle rectangle
skinparam DefaultTextAlignment center

actor "Usuário" as usuario

node "Dispositivo do Usuário" #white {
  artifact "Navegador Web" as browser
}

node "Servidor Front-end\nNode.js / Vite" as frontend #white {
  artifact "Aplicação Vue.js\nMusicáudio Front" as vue
  component "Axios" as axios
}

node "Servidor Back-end" as backend #white {

 component "Aplicação Spring Boot" as spring {

  component "Controllers REST" as controllers
  component "Spring Security" as security
  component "Services" as services
  component "Repositories JPA" as repositories
 }

  database "Banco de Dados\nPostgreSQL\nMusicáudio" as postgres #white 
}



usuario --> browser : acessa sistema
browser --> vue : HTTPS

vue --> axios

axios --> security : Authorization: Bearer JWT
security --> controllers : autenticação e autorização
controllers --> services
services --> repositories
repositories --> postgres : JDBC/JPA


note right of frontend
Front-end desenvolvido com:
- Vue.js
- Vue Router
- Pinia
- Axios
- Vite
end note

note right of backend
Back-end desenvolvido com:
- Spring Boot
- Spring Web
- Spring Data JPA
- Spring Security
- JWT
end note

@enduml