@startuml gerenciar_curso

title Diagrama de Estado - Caso de Uso: Gerenciar Cursos\nMusicáudio

skinparam backgroundColor lightyellow

skinparam nodesep 150

left to right direction

'CRUD curso
[*] --> Rascunho : criar curso
Rascunho : curso é visto apenas pelo criador
Rascunho --> Publicado : publicar
Publicado : curso é visto por outros usuários e pode ser comprado

state c <<choice>>
Publicado --> c : remover curso
c --> Despublicado : [possui compras]
Despublicado : visível para o dono, e para quem tem acesso
Despublicado --> [*]

c --> Rascunho : [não possui compras]
Rascunho --> Curso_Desativado : excluir
Curso_Desativado --> [*]

@enduml