@startuml
title Diagrama de Classes Controllers - Musicáudio

!pragma layout elk

left to right direction

skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 100

skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam shadowing false

package "controller" {

    'USUARIO
    class UsuarioController <<RestController>> {
        -usuarioService: UsuarioService
        +novoUsuario(usuario: Usuario): ResponseEntity<UsuarioResponseDTO>
        +getUsuarios(): ResponseEntity<List<UsuarioResponseDTO>>
        +getUsuarioPorId(id: Long): ResponseEntity<UsuarioResponseDTO>
        +getUsuarioPorCredencial(id: Long) : ResponseEntity<UsuarioResponseDTO>
        +atualizarUsuarioPorId(id: Long, usuario: Usuario): ResponseEntity<UsuarioResponseDTO>
        +apagarUsuario(id: Long): ResponseEntity<?>
    }

    'CURSO
    class CursoController <<RestController>> {
        -cursoService: CursoService
        +criarCurso(dto: CursoRequestDTO): ResponseEntity<CursoResponseDTO>
        +getCursos(): ResponseEntity<List<CursoResponseDTO>>
        +getCursoPorId(id: Long): ResponseEntity<CursoResponseDTO>
        +getCursosPorInstrutor(usuarioId: Long): ResponseEntity<List<CursoResponseDTO>>
        +atualizarCurso(id: Long, dto: CursoRequestDTO): ResponseEntity<CursoResponseDTO>
        +publicarCurso(id: Long): ResponseEntity<CursoResponseDTO>
        +apagarCurso(id: Long): ResponseEntity<?>
    }

    'MODULO
    class ModuloController <<RestController>> {
        -moduloService: ModuloService
        +criarModulo(cursoId: Long, dto: ModuloRequestDTO): ResponseEntity<ModuloResponseDTO>
        +getModulosPorCurso(cursoId: Long): ResponseEntity<List<ModuloResponseDTO>>
        +getModuloPorId(id: Long): ResponseEntity<ModuloResponseDTO>
        +atualizarModulo(id: Long, dto: ModuloRequestDTO): ResponseEntity<ModuloResponseDTO>
        +ativarDesativarModulo(id: Long, dto: AtivarStatusDTO): ResponseEntity<ModuloResponseDTO>
        +apagarModulo(id: Long): ResponseEntity<?>
    }

    'AULA
    class AulaController <<RestController>> {
        -aulaService: AulaService
        +criarAula(cursoId: Long, dto: AulaRequestDTO): ResponseEntity<AulaResponseDTO>
        +getAulasPorModulo(cursoId: Long): ResponseEntity<List<AulaResponseDTO>>
        +getAulaPorId(id: Long): ResponseEntity<AulaResponseDTO>
        +atualizarAula(id: Long, dto: AulaRequestDTO): ResponseEntity<AulaResponseDTO>
        +ativarDesativarAula(id: Long, dto: AtivarStatusDTO): ResponseEntity<AulaResponseDTO>
        +apagarAula(id: Long): ResponseEntity<?>
    }

    'MATERIAL
    class MaterialController <<RestController>> {
        -materialService: MaterialService
        +criarMaterial(aulaId: Long, dto: MaterialRequestDTO): ResponseEntity<MaterialResponseDTO>
        +getMateriaisPorAula(aulaId: Long): ResponseEntity<List<MaterialResponseDTO>>
        +getMaterialPorId(id: Long): ResponseEntity<MaterialResponseDTO>
        +atualizarMaterial(id: Long, dto: MaterialRequestDTO): ResponseEntity<MaterialResponseDTO>
        +ativarDesativarMaterial(id: Long, dto: AtivarStatusDTO): ResponseEntity<MaterialResponseDTO>
        +apagarMaterial(id: Long): ResponseEntity<?>
    }

    'COMPRA
    class CompraController <<RestController>> {
        -compraService: CompraService
        +iniciarCompra(dto: CompraRequestDTO): ResponseEntity<CompraResponseDTO>
        +adicionarItem(compraId: Long, dto: CursoRequestDTO): ResponseEntity<CursoResponseDTO>
        +finalizarCompra(compraId: Long): ResponseEntity<CompraResponseDTO>
        +getComprasPorUsuario(usuarioId: Long): ResponseEntity<List<CompraResponseDTO>>
        +getCompraPorId(id: Long): ResponseEntity<CompraResponseDTO>
        +cancelarCompra(id: Long): ResponseEntity<?>
    }

    'PAGAMENTO
      class PagamentoController <<RestController>> {
        -pagamentoService: PagamentoService
        +processarPagamento(compraId: Long, dto: PagamentoRequestDTO): ResponseEntity<PagamentoResponseDTO>
        +getPagamentoPorId(id: Long): ResponseEntity<PagamentoResponseDTO>
        +getPagamentosPorCompra(compraId: Long): ResponseEntity<List<PagamentoResponseDTO>>
        +atualizarStatusPagamento(id: Long, dto: AtualizarStatusPagamentoDTO): ResponseEntity<PagamentoResponseDTO>
        +estornarPagamento(id: Long): ResponseEntity<PagamentoResponseDTO>
    }

    'MATRICULA
    class MatriculaController <<RestController>> {
        -matriculaService: MatriculaService
        +criarMatricula(dto: MatriculaRequestDTO): ResponseEntity<MatriculaResponseDTO>
        +getMatriculasPorUsuario(usuarioId: Long): ResponseEntity<List<MatriculaResponseDTO>>
        +getMatriculaPorId(id: Long): ResponseEntity<MatriculaResponseDTO>
        +verificarMatricula(usuarioId: Long, cursoId: Long): ResponseEntity<Boolean>
        +ativarDesativarMatricula(id: Long, dto: AtivarStatusDTO): ResponseEntity<MatriculaResponseDTO>
        +apagarMatricula(id: Long): ResponseEntity<?>
    }

    'CREDENCIAL
    class CredencialController <<RestController>> {
        -auttenticacaoService: CredencialService
        +novaCredencial(credencial: Credencial): ResponseEntity<CredencialResponseDTO>
        +getCredenciais(): ResponseEntity<List<CredencialResponseDTO>>
        +getCredencialPorId(id: Long): ResponseEntity<CredencialResponseDTO>
        +atualizarCredencialPorId(id: Long, credencial: Credencial): ResponseEntity<CredencialResponseDTO>
        +apagarCredencial(id: Long): ResponseEntity<?>
    }

    'LOGIN
    class AuthenticationController <<RestController>> {
        -authenticationManager: AuthenticationManager
        -tokenService: TokenService
        +login(dados: LoginRequestDTO): ResponseEntity<?>
    }
}

' Controllers

   'USUARIO
UsuarioController --> UsuarioService

    'CURSO
CursoController --> CursoService

    'MODULO
ModuloController --> ModuloService

    'AULA
AulaController --> AulaService

    'MATERIAL
MaterialController --> MaterialService

    'COMPRA
CompraController --> CompraService

    'PAGAMENTO
PagamentoController --> PagamentoService

    'MATRICULA
MatriculaController --> MatriculaService

    'TOKEN
AuthenticationController --> TokenService

    'CREDENCIAL
CredencialController --> CredencialService
@enduml