@startuml
title Diagrama de Classes Entidades e Repositórios - Musicáudio

!pragma layout elk

left to right direction

skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 100

skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam shadowing false

package "model.entity" {

    class Usuario <<Entity>> {
        -id: Long
        -nome: String
        -sobrenome: String
        -cpf: String
        -data_nascimento: String
        -telefone: String
        -foto_perfil : String
        -biografia : String
        -data_criacao : DateTime
        -data_atuaizacao : DateTime
        -data_delecao : DateTime
        -Credencial : Credencial
    }

    class Credencial <<Entity>> {
        -id: Long
        -email:String
        -senha: String
        -admin: boolean
    }
    
    class Curso <<Entity>> {
        -id: Long
        -nome: String
        -descricao: String
        -preco: double
        -imagem_capa: String
        -nivel: String
        -status: String
        -data_criacao: DateTime
        -data_atualizacao: DateTime
        -data_publicacao: DateTime
        -data_delecao : DateTime
    }

    class Modulo <<Entity>> {
        -id: Long
        -nome: Long
    }

    class Aula <<Entity>> {
        -id: Long
        -titulo: String
        -descricao: String
        -ativo: boolean
        -data_criacao: DateTime
        -data_atualizacao: DateTime
        -data_delecao : DateTime
    }

    class Material <<Entity>> {
        -id: Long
        -titulo: String
        -descricao: String
        -tipo: String
        -url_arquivo: String
        -ativo: Boolean
        -data_upload: DateTime
        -data_delecao : DateTime
    }

    class Compra <<Entity>> {
        -id: Long
        -valor_total: float
        -status: boolean
        -data_compra: DateTime
        -data_delecao : DateTime
    }

    class Pagamento <<Entity>> {
        -id: Long
        -metodo: String
        -status: String
        -codigo_transacao: Long
        -data_delecao : DateTime
    }

    class Matricula <<Entity>> {
        -id: Long
        -data_matricula: DateTime
        -ativo: boolean
        -data_delecao : DateTime
    }
}

package "model.repository" {

    interface UsuarioRepository <<Repository>> 

    interface CredencialRepository <<Repository>>

    interface CursoRepository <<Repository>>

    interface ModuloRepository <<Repository>>

    interface AulaRepository <<Repository>>

    interface MaterialRepository <<Repository>>

    interface CompraRepository <<Repository>>

    interface PagamentoRepository <<Repository>>

    interface MatriculaRepository <<Repository>>

    interface JpaRepository<T, ID> <<Spring Data>>
}

' Repositories

UsuarioRepository --|> JpaRepository
CursoRepository --|> JpaRepository
ModuloRepository --|> JpaRepository
AulaRepository --|> JpaRepository
MaterialRepository --|> JpaRepository
CompraRepository --|> JpaRepository
PagamentoRepository --|> JpaRepository
MatriculaRepository  --|> JpaRepository
CredencialRepository --|> JpaRepository

UsuarioRepository ..> Usuario
CursoRepository ..> Curso
ModuloRepository ..> Modulo
AulaRepository ..> Aula
MaterialRepository ..> Material
CompraRepository ..> Compra
PagamentoRepository ..> Pagamento
MatriculaRepository ..> Matricula
CredencialRepository ..> Credencial
@enduml