@startuml

title Diagrama de Classes Segurança - Musicáudio

package "security" {

    class CustomUserDetails {
        -autenticacaoService: AutenticacaoService
        +CustomUserDetails(usuarioService: UsuarioService)
        +loadUserByUsername(identificador: String): UserDetails
    }

    class SecurityFilter <<Component>> {
        -tokenService: TokenService
        -userDetailsService: UserDetailsService
        +doFilterInternal(request: HttpServletRequest, response: HttpServletResponse, filterChain: FilterChain): void
        -recuperarToken(request: HttpServletRequest): String
    }

    class FilterChainConfig <<Configuration>> {
        +securityFilterChain(http: HttpSecurity, filter: SecurityFilter): SecurityFilterChain
        +passwordEncoder(): PasswordEncoder
        +authenticationManager(configuration: AuthenticationConfiguration): AuthenticationManager
        +userDetailsService(autenticacaoService: AutenticacaoService): UserDetailsService
        +corsConfigurationSource(): CorsConfigurationSource
    }
}

' Segurança

CustomUserDetails --> AutenticacaoService
CustomUserDetails ..> Autenticacao

SecurityFilter --> TokenService
SecurityFilter --> CustomUserDetails

FilterChainConfig --> SecurityFilter
FilterChainConfig --> CustomUserDetails
FilterChainConfig --> AutenticacaoService

@enduml