@startuml Gerenciar Perfil

skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 200
skinparam sequenceGroupBorderThickness 1.5
skinparam sequenceGroupFontStyle bold
skinparam noteFontSize 11
skinparam ParticipantFontStyle bold

title Diagrama de Sequência - Caso de Uso: Gerenciar Perfil\nMusicáudio v1.0

skinparam backgroundColor lightyellow

actor "Usuário" as USR

box "Camada Vue JS" #LightGreen
    boundary "Views JS" as VUE
end box

box "Camada de Segurança" #LightYellow
    participant "SecurityFilter\n(JWT)" as SEC
end box

box "Camada de Controle" #LightBlue
    control "ContaController" as CC
end box

box "Camada de Serviço" #LightPink
    entity "ContaService" as CS
end box

box "Camada de Persistência" #LightGrey
    database "CredencialRepository" as AR
    database "UsuarioRepository" as UR
end box

' FA2 - VISUALIZAR PERFIL (usuário comum)

== FA2: Visualizar Perfil (Usuário Autenticado) ==
note over USR: Pré-condição: autenticado via JWT

USR -> VUE : Visualizar Perfil

activate VUE

VUE -> SEC : GET /contas/minha-conta\nAuthorization: Bearer <token>
activate SEC
    SEC -> SEC : recuperarToken(request)
    SEC -> SEC : tokenService.validarToken(token)

    alt #white S1 - Token inválido / sem permissão
        SEC --> VUE : 403 Forbidden
    else Token válido
        SEC -> SEC : SecurityContextHolder\n.setAuthentication(auth)
        SEC -> CC : repassa requisição autenticada
         deactivate SEC
         activate CC
    end

    CC -> CS : getContaPorEmail(emailLogado)
    activate CS
        CS -> AR : findByEmail(emailLogado)
        activate AR
        AR --> CS : Credencial
        deactivate AR

        CS -> UR : findUsuarioByCredencial_Id(credencialId)
        activate UR
        UR --> CS : Usuario
        deactivate UR

        alt #white S1 - Conta não encontrada
            CS --> CC : EntityNotFoundException\n("Não foi possível encontrar a conta")
            CC --> VUE : 400 Bad Request\n{ mensagem de erro }
        else Conta encontrada
            CS --> CC : ContaResponseDTO
            deactivate CS
            CC --> VUE : 200 OK\n{ ContaResponseDTO }
        end
deactivate CC
deactivate VUE

@enduml