@startuml Gerenciar Curso

skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 200
skinparam sequenceGroupBorderThickness 1.5
skinparam sequenceGroupFontStyle bold
skinparam noteFontSize 11
skinparam ParticipantFontStyle bold

title Diagrama de Sequência - Caso de Uso: Gerenciar Curso\nParte Admin\nMusicáudio v1.0

actor "Administrador" as ADM

box "Camada Vue JS" #LightGreen
    boundary "Views JS" as VUE
end box

box "Camada de Segurança" #LightYellow
    participant "SecurityFilter\n(JWT)" as SEC
end box

box "Camada de Controle" #LightBlue
    control "CursoController" as CC
end box

box "Camada de Serviço" #LightPink
    entity "AutenticacaoService" as AS
    entity "UsuarioService" as US
    entity "CursoService" as CS
end box

box "Camada de Persistência" #LightGrey
    database "AutenticacaoRepository" as AR
    database "UsuarioRepository" as UR
    database "CursoRepository" as CR
end box

' FA1-Admin - LISTAR TODOS OS CURSOS

== FA1-Admin: Listar Todos os Cursos ==
note over ADM: Pré-condição: autenticado como ADMIN

ADM -> VUE : Listar Cursos
activate VUE

VUE -> SEC : GET /cursos\nAuthorization: Bearer <token>
activate SEC
    SEC -> SEC : recuperarToken(request)
    SEC -> SEC : tokenService.validarToken(token)

    alt #white S1 - Token inválido / sem autenticação
        SEC --> VUE : 403 Forbidden
    else Token válido
        SEC -> SEC : SecurityContextHolder\n.setAuthentication(auth)
        SEC -> CC : repassa requisição autenticada
         deactivate SEC
         activate CC
    end

    CC -> CS : getCursos()
    activate CS
        CS -> CR : findAll()
        CR --> CS : List<Curso>
        CS --> CC : List<Curso>
    deactivate CS

    CC --> VUE : 200 OK\n{ List<CursoResponseDTO> }
deactivate CC
deactivate VUE

' FA2-Admin - LISTAR CURSO POR ID

== FA2-Admin: Listar Curso Por Id ==

ADM -> VUE : Visualizar Curso por Id
activate VUE
VUE -> SEC : GET /cursos/{id}\nAuthorization: Bearer <token>
activate SEC
    SEC -> SEC : recuperarToken(request)
    SEC -> SEC : tokenService.validarToken(token)

    alt #white S1 - Token inválido / sem autenticação
        SEC --> VUE : 403 Forbidden
    else Token válido
        SEC -> SEC : SecurityContextHolder\n.setAuthentication(auth)
        SEC -> CC : repassa requisição autenticada
         deactivate SEC
         activate CC
    end
CC -> CS : getCursoPorId(id)
activate CS
CS -> CR : findById(id)
    alt #white S1 - Curso não encontrado
            CR --> CS : EntityNotFoundException
            CS --> CC : EntityNotFoundException\n("Curso não encontrado")
            CC --> VUE : 400 Bad Request\n{ "Curso não encontrado" }
    else Curso existe
        CR --> CS : Curso
        CS --> CC : Curso
        deactivate CS
        CC --> VUE : 200 OK\n{CursoResponseDTO}
        deactivate CC
    end
deactivate VUE

' FA3-Admin - EDITAR QUALQUER CURSO

== FA3-Admin: Editar Qualquer Curso ==
note over ADM: Pré-condição: autenticado como ADMIN

ADM -> VUE : Editar Curso
activate VUE

VUE -> SEC : PUT /cursos/{id}\nAuthorization: Bearer <token>\n{ dados atualizados }
activate SEC
    SEC -> SEC : recuperarToken(request)
    SEC -> SEC : tokenService.validarToken(token)

    alt #white S1 - Token inválido / sem autenticação
        SEC --> VUE : 403 Forbidden
    else Token válido
        SEC -> SEC : SecurityContextHolder\n.setAuthentication(auth)
        SEC -> CC : repassa requisição autenticada
         deactivate SEC
         activate CC
    end

activate CC

    CC -> CS : atualizarCurso(id, cursoAtualizado)
    activate CS
        CS -> CS : validarCurso(cursoAtualizado)

        alt #white S1 - Dados obrigatórios não preenchidos
            CS --> CC : IllegalArgumentException
            CC --> VUE : 400 Bad Request\n{ mensagem de erro }
        else S2 - Dados inválidos
            CS --> CC : IllegalArgumentException
            CC --> VUE : 400 Bad Request\n{ mensagem de erro }
        else Dados válidos
            CS -> CS : getCursoPorId(id)
            CS -> CR : findById(id)
            CR --> CS : Curso atual
            CS -> CR : save(curso)
            CR --> CS : Curso atualizado
            CS --> CC : Curso
               deactivate CS
            CC --> VUE : 200 OK\n{ CursoResponseDTO atualizado }
            deactivate CC
        end
deactivate VUE

' FA4-Admin - REMOVER QUALQUER CURSO

== FA4-Admin: Remover Qualquer Curso ==
note over ADM: Pré-condição: autenticado como ADMIN

ADM -> VUE : Remover Curso
activate VUE

VUE -> SEC : DELETE /cursos/{id}\nAuthorization: Bearer <token>
activate SEC
    SEC -> SEC : recuperarToken(request)
    SEC -> SEC : tokenService.validarToken(token)

    alt #white S1 - Token inválido / sem autenticação
        SEC --> VUE : 403 Forbidden
    else Token válido
        SEC -> SEC : SecurityContextHolder\n.setAuthentication(auth)
        SEC -> CC : repassa requisição autenticada
         deactivate SEC
         activate CC
    end

activate CC
    CC -> CS : apagarCurso(id)
    activate CS
        CS -> CR : existsById(id)

        alt #white S1 - Curso não encontrado
            CR --> CS : false
            CS --> CC : IllegalArgumentException\n("Curso não encontrado")
            CC --> VUE : 400 Bad Request\n{ "Curso não encontrado" }
        else Curso existe
            CR --> CS : true
            CS -> CR : deleteById(id)
            CR --> CS : OK
            CS --> CC : true
               deactivate CS
            CC --> VUE : 204 No Content
               deactivate CC
        end
 

deactivate VUE

@enduml
